development: &development
  developer: true
  base: "http://localhost:3000"
  return_to: "/payments/efetuado"
  email: log@korewa.com.br

test:
  <<: *development

production:
  authenticity_token: 0F6D6FC847E14AB4BEE3FAAB98B4E861
  email: sussumu@hdcomputers.com.br
  return_to: "http://www.licell.com.br/payments/efetuado"
