development: &development
  developer: true
  base: "http://localhost:3000"
  return_to: "/payments/efetuado"
  email: log@korewa.com.br

test:
  <<: *development

production:
  authenticity_token: 09069F2462F243E783326AC2E63F9DA5
  email: alessandra@hdcomputers.com.br
  return_to: "http://www.licell.com.br/payments/efetuado"
