development: &development
  developer: true
  base: "http://localhost:3000"
  return_to: "/payments/efetuado"
  email: log@korewa.com.br

test:
  <<: *development

production:
  authenticity_token: C31EFEA28C874E85ADB8DFAAD5CBD576
  email: log@korewa.com.br
  return_to: "http://www.licell.com.br/payments/efetuado"
