development: &development
  developer: true
  base: "http://localhost:3000"
  return_to: "/payments/efetuado"
  email: bruformulasatibaia@uol.com.br

test:
  <<: *development

production:
  authenticity_token: C31EFEA28C874E85ADB8DFAAD5CBD576
  email: bruformulasatibaia@uol.com.br
  return_to: "http://www.farmaciaecovita.com.br/payments/efetuado"
